name: Run Zap Scan

on:
  push:
    branches:
      - main

jobs:
  DAST_zap_scan:
    name: Scan the Web Application with ZAP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.ZAP_PAT }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'TARGET_URL' # Replace with your target URL
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
